import java.util.Scanner;
class G6
{
    public static void main(String args[])
    {
        int a,b,c,d,e,f;
        Scanner sc=new Scanner(System.in);
       { a=sc.nextInt();
        b=sc.nextInt();
        c=sc.nextInt();
        d=sc.nextInt();
        e=sc.nextInt();
        f=sc.nextInt();
       }
       if(a>b)
       {
           if(a>c)
           {
               if(a>d)
               {
                   if(a>e)
                   {
                       if(a>f)
                       {
                           System.out.println(a);
                       }
                       else
                       {
                        System.out.println(f);
                       }
                   }
                   else
                   {
                       if(e>f)
                       {
                        System.out.println(e);
                       }
                       else
                       {
                        System.out.println(f);
                       }
                   }
               }
               else
               {
                   if(d>e)
                   {
                       if(d>f)
                       {
                        System.out.println(d);
                       }
                       else
                       {
                        System.out.println(f);
                       }
                   }
                   else
                   {
                       if(e>f)
                       {
                           System.out.println(e);
                       }
                       else
                       {
                        System.out.println(f);
                       }
                   }
               }
           }
           else
           {
               if(c>d)
               {
                   if(c>e)
                   {
                       if(c>f)
                       {
                        System.out.println(c);
                       }
                       else
                       {
                        System.out.println(f);
                       }
                   }
                   else
                   {
                       if(d>e)
                       {
                           if(d>f)
                           {
                            System.out.println(d);
                           }
                           else
                           {
                            System.out.println(f);
                           }
                       }
                       else
                       {
                           if(e>f)
                           {
                            System.out.println(e);
                           }
                           else
                           {
                            System.out.println(f);
                           }
                       }
                   }
               }
           }
       }
       else
       {
           if(b>c)
           {
               if(b>d)
               {
                   if(b>e)
                   {
                       if(b>f)
                       {
                        System.out.println(b);
                       }
                       else
                       {
                        System.out.println(f);
                       }
                   }
                   else
                   {
                       if(e>f)
                       {
                        System.out.println(e);
                       }
                       else
                       {
                        System.out.println(f);
                       }
                   }
               }
               else
               {
                   if(d>e)
                   {
                       if(d>f)
                       {System.out.println(d);}
                       else
                       {
                        System.out.println(f);
                       }
                   }
                   else
                   {
                       if(e>f)
                       {
                        System.out.println(e);
                       }
                       else
                       {
                        System.out.println(f);
                       }
                   }
               }
           }
           else
           {
               if(c>d)
               {
                   if(c>e)
                   {
                       if(c>f)
                       {
                        System.out.println(c);
                       }
                       else
                       {
                        System.out.println(f);
                       }
                   }
                   else
                   {
                       if(d>e)
                       {
                           if(d>f)
                           {
                            System.out.println(d);
                           }
                           else
                           {
                            System.out.println(f);
                           }
                       }
                       else
                       {
                           if(e>f)
                           {
                            System.out.println(e);
                           }
                           else
                           {
                            System.out.println(f);
                           }
                       }
                   }
               }
               else
               {
                   if(d>e)
                   {
                       if(d>f)
                       {
                        System.out.println(d);
                       }
                       else
                       {
                        System.out.println(f);
                       }
                   }
                   else
                   {
                       if(e>f)
                       {
                        System.out.println(e);
                       }
                       else
                       {
                        System.out.println(f);
                       }
                   }
               }

           }
       }
    }
}       