import java.util.Scanner;
class G7
{
    public static void main(String args[])
    {
        int a,b,c,d,e,f,h;
        Scanner sc=new Scanner(System.in);
       { a=sc.nextInt();
        b=sc.nextInt();
        c=sc.nextInt();
        d=sc.nextInt();
        e=sc.nextInt();
        f=sc.nextInt();
        h=sc.nextInt();
       }
       if(a>b)
       {
           if(a>c)
           {
               if(a>d)
               {
                   if(a>e)
                   {
                       if(a>f)
                       {
                           if(a>h)
                           {
                               System.out.println(a);
                           }
                           else
                           {
                               System.out.println(h);
                           }
                       }
                       else
                       {
                           if(f>h)
                           {
                            System.out.println(f);
                           }
                           else
                           {
                            System.out.println(h);
                           }
                       }
                   }
                   else
                   {
                       if(e>f)
                       {
                           if(e>h)
                           {
                            System.out.println(e);
                           }
                           else
                           {
                            System.out.println(h);
                           }
                       }
                       else
                       {
                           if(f>h)
                           {
                            System.out.println(f);
                           }
                           else
                           {
                            System.out.println(h);
                           }
                       }
                   }
               }
               else
               {
                   if(d>e)
                   {
                       if(d>f)
                       {
                           if(d>h)
                           {
                            System.out.println(d);
                           }
                           else
                           {
                            System.out.println(h);
                           }
                       }
                       else
                       {
                           if(f>h)
                           {
                            System.out.println(f);
                           }
                           else
                           {
                            System.out.println(h);
                           }
                       }
                   }
                   else
                   {
                       if(e>f)
                       {
                           if(e>h)
                           {
                            System.out.println(e);
                           }
                           else
                           {
                            System.out.println(h);
                           }
                       }
                       else
                       {
                           if(f>h)
                           {
                            System.out.println(f);
                           }
                           else
                           {
                            System.out.println(h);
                           }
                       }
                   }
               }
           }
           else
           {
               if(c>d)
               {
                   if(c>e)
                   {
                       if(c>f)
                       {
                           if(c>h)
                           {
                            System.out.println(c);
                           }
                           else
                           {
                            System.out.println(h);
                           }
                       }
                       else
                       {
                           if(f>h)
                           {
                            System.out.println(f);
                           }
                           else
                           {
                            System.out.println(h);
                           }

                       }
                   }
                   else
                   {
                       if(e>f)
                       {
                           if(e>h)
                           {
                            System.out.println(e);
                           }
                           else
                           {
                            System.out.println(h);
                           }
                       }
                       else
                       {
                          if(e>h)
                          {
                            System.out.println(e);
                          }
                          else
                          {
                            System.out.println(h);
                          }
                       }
                   }
               }
               else
               {
                   if(d>e)
                   {
                    if(d>f)
                    {
                        if(d>h)
                        {
                         System.out.println(d);
                        }
                        else
                        {
                         System.out.println(h);
                        }
                    }
                    else
                    {
                        if(f>h)
                        {
                         System.out.println(f);
                        }
                        else
                        {
                         System.out.println(h);
                        }
                    }
                   }
                   else
                   {
                       if(e>f)
                       {
                           if(e>h)
                           {
                            System.out.println(e);
                           }
                           else
                           {
                            System.out.println(h);
                           }
                       }
                       else
                       {
                           if(f>h)
                           {
                            System.out.println(f);
                           }
                           else
                           {
                            System.out.println(h);
                           }
                       }
                   }

                }
            }
        } 
        else
        {
            if(b>c)
            {
                if(b>d)
                {
                    if(b>e)
                    {
                        if(b>f)
                        {
                            if(b>h)
                            {
                                System.out.println(b);
                            }
                            else
                            {
                                System.out.println(h);
                            }
                        }
                        else
                        {
                            if(f>h)
                            {
                                System.out.println(f);
                            }
                            else
                            {
                                System.out.println(h);
                            }
                        }
                    }
                    else
                    {
                        if(e>f)
                        {
                            if(e>h)
                            {
                                System.out.println(e);
                            }
                            else
                            {
                                System.out.println(h);
                            }
                        }
                        else
                        {
                            if(f>h)
                            {
                                System.out.println(f);
                            }
                            else
                            {
                                System.out.println(h);
                            }
                        }
                    }
                }
                else
                {
                    if(d>e)
                    {
                        if(d>f)
                        {
                            if(d>h)
                            {
                                System.out.println(d);
                            }
                            else
                            {
                                System.out.println(h);
                            }
                        }
                        else
                        {
                            if(f>h)
                            {
                                System.out.println(f);
                            }
                            else
                            {
                                System.out.println(h);
                            }
                        }
                    }
                    else
                    {
                        if(e>f)
                        {
                            if(e>h)
                            {
                                System.out.println(e);
                            }
                            else
                            {
                                System.out.println(h);
                            }
                        }
                        else
                        {
                            if(f>h)
                            {
                                System.out.println(f);
                            }
                            else
                            {
                                System.out.println(h);
                            }
                        }
                    }
                }
            }
            else
            {}
        }  
    }
   
    
}       